# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: Prof. Jinpeng Chen
tagline: Social Media & Data Mining · Recommender Systems · Large Language Models · Intelligent Transportation & Spatiotemporal Forecasting
url: "https://your-github-username.github.io"
baseurl: ""
lang: en
timezone: Asia/Shanghai

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

plugins:
  - jekyll-scholar
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

scholar:
  source: _bibliography
  bibliography: papers.bib
  style: ieee
  locale: en
  sort_by: year
  order: descending
  bibliography_template: bib_entry

nav:
  - name: Publications
    url: /publications/
  - name: Service
    url: /service/

author:
  name: Prof. Jinpeng Chen
  email: you@bupt.edu.cn
  affiliation: School of Computer Science (National Model Software College), Beijing University of Posts and Telecommunications


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
